name: AV-SphereEngine

on:
  #pull_request:
    #types: [closed]
  workflow_call:
  push:
    paths:
      - ".github/workflows/AV-sphereengine.yml"
      - "sphereengine/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven-checking dev
        run: mvn clean install

      - name: Bump versions sphereengines
        id: bump
        #if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'Merge pull request')
        uses: ./.github/actions/semversion-calculation
        with:
          component: "sphereengine"
          versions-json: ${{ vars.JSON_VERSIONS }}  

      - name: Upload to artifact 
        run: |
           echo "Submitting solution to Sphere Engine API..."
