name: Retrieving secrets
on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

  call-deploycheck:
    needs: checkout  # Fixed indentation
    uses: dsidevops2024/ArtifactVersioning/.github/workflows/deploy-check.yml@main
    with:
        environment: production
    secrets:
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
